name: cell-health
channels:
- conda-forge
dependencies:
- conda-forge::python
- conda-forge::pandas
- conda-forge::xlrd
- conda-forge::numpy
- conda-forge::requests
- conda-forge::scikit-learn
- conda-forge::dask-ml
- conda-forge::umap-learn
- conda-forge::joblib
- conda-forge::matplotlib
- conda-forge::seaborn
- conda-forge::plotnine
- conda-forge::jupyter
- conda-forge::ipykernel
- conda-forge::nb_conda_kernels
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::rpy2
- conda-forge::simplegeneric
- conda-forge::pip
- conda-forge::r-base
- conda-forge::r-stringr
- conda-forge::r-dplyr
- conda-forge::r-tidyr
- conda-forge::r-magrittr
- conda-forge::r-tibble
- conda-forge::r-docopt
- conda-forge::r-purrr
- conda-forge::r-readr
- conda-forge::r-readxl
- conda-forge::r-drc
- conda-forge::r-ggplot2
- conda-forge::r-cowplot
- conda-forge::r-ggrepel
- conda-forge::r-gridextra
- conda-forge::r-svglite
- conda-forge::r-irkernel
- conda-forge::r-optparse
- conda-forge::r-platetools
- conda-forge::r-curl
- conda-forge::r-futile.logger
- conda-forge::r-knitr
- pip:
  - git+https://github.com/cytomining/pycytominer